import { businessToday, expect, seed, signInOperator, test, opsApi } from './fixtures';

test('Kitchen assets, stock, sales and costs reconcile with business profit on phone and desktop', async ({page,context}) => {
  const seeded=seed('operator');const api=opsApi(seeded.operator_token);const now=businessToday();
  await signInOperator(context,seeded.operator_token);
  await page.goto('/locations');
  await page.getByRole('button',{name:'Add a location',exact:true}).first().click();
  await page.getByLabel('Location name',{exact:true}).fill('Kitchen A');
  await page.getByRole('button',{name:'Create location',exact:true}).click();
  await page.getByRole('link',{name:'Kitchen A',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Kitchen A',exact:true})).toBeVisible();
  const id=new URL(page.url()).pathname.split('/').pop()!;
  await page.locator('summary').filter({hasText:/^Allocate stock$/}).click();
  await page.getByLabel('Buying cost per unit (TZS)',{exact:true}).fill('10000');
  await page.getByLabel('Quantity given to this location',{exact:true}).fill('20');
  await page.getByRole('button',{name:'Allocate stock',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Stock at this location · current'}).locator('..')).toContainText('20 bird');
  await page.getByText('Record daily sales',{exact:true}).click();
  await page.getByLabel('Quantity sold',{exact:true}).fill('12');
  await page.getByLabel('Selling price per unit (TZS)',{exact:true}).fill('15000');
  await page.getByLabel('Money collected now (TZS)',{exact:true}).fill('180000');
  await page.getByRole('button',{name:'Record location sale',exact:true}).click();
  await expect(page.getByLabel('Location summary')).toContainText('TZS 180,000');
  await page.getByRole('button',{name:'Record expense',exact:true}).click();
  const expenseDialog=page.getByRole('dialog');
  await expenseDialog.getByRole('combobox',{name:'Category',exact:true}).selectOption('labour');
  await expenseDialog.getByLabel('What for',{exact:true}).fill('Kitchen staff');
  await expenseDialog.getByLabel('Amount (TZS)',{exact:true}).fill('12000');
  await expenseDialog.getByRole('radio',{name:'Owed',exact:true}).check();
  await expenseDialog.getByRole('button',{name:'Save expense',exact:true}).click();
  await expect(page.getByLabel('Location summary')).toContainText('TZS 48,000');
  await page.locator('summary').filter({hasText:/^Register an asset$/}).click();
  await page.getByLabel('Asset name',{exact:true}).fill('BBQ stove');
  await page.getByLabel('Purchase cost (TZS)',{exact:true}).fill('360000');
  await page.getByLabel('Useful life (months)',{exact:true}).fill('12');
  await page.getByRole('button',{name:'Register asset',exact:true}).click();
  await expect(page.getByRole('heading',{name:'BBQ stove',exact:true})).toBeVisible();
  const result=await api.get<{net_profit:string;depreciation:string;investment:string}>(`/ops/locations/${id}?start=${now}&end=${now}`);
  expect(Number(result.investment)).toBe(360000);
  expect(Number(result.net_profit)).toBeCloseTo(48000-Number(result.depreciation),2);
  const business=await api.get<{net_profit:string}>(`/ops/finance/profit?start=${now}&end=${now}`);
  expect(Number(business.net_profit)).toBeCloseTo(Number(result.net_profit),2);
  await page.setViewportSize({width:390,height:844});
  await expect(page.getByRole('button',{name:'Record expense',exact:true})).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);
});
